>>> import dis
>>> act = maker(4)
>>> dis.dis(act)
 44           0 LOAD_FAST                0 (X)
              2 LOAD_DEREF               0 (N)
              4 BINARY_MULTIPLY
              6 RETURN_VALUE
>>> dis.dis(clsmaker.__call__)
 51           0 LOAD_FAST                1 (X)
              2 LOAD_FAST                0 (self)
              4 LOAD_ATTR                0 (N)
              6 BINARY_MULTIPLY
              8 RETURN_VALUE
>>> act = maker(8)

>>> print(act(19))
X=19,N=8
152

>>> maker(9)(7)
X=7,N=9
63





